baseURL = "https://leanderpeter.de/"
languageCode = "en-us"
title = "Leander Peter"
theme = "PaperMod"

[params]
  author = "Leander Peter"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  description = "I break and build stuff -"

  shareButtons = ["linkedin"]

  [params.profileMode]
    enabled = true
    title = "Leander Peter"
    subtitle = "I engineer, build and break stuff."
    buttons = [
      { name = "Blog", url = "/posts/" },
      { name = "About", url = "/about/" }
    ]

  [params.mermaid]
    theme = "dark"
    align = "center"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2


[[params.socialIcons]]
name = "github"
url = "https://github.com/leanderpeter"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/leander-peter-943b021a7/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"